language: rust
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/rust
    - $HOME/.cargo

rust:
  - stable

before_script:
  - |
      git clone https://github.com/sstephenson/bats/ &&
      (cargo install --git https://github.com/semantic-rs/semantic-rs || true) &&
      mkdir $HOME/workspace &&
      cp -ar $TRAVIS_BUILD_DIR/fixtures/* $HOME/workspace/ &&
      export PATH=$(pwd)/bats/bin:$HOME/.cargo/bin:$PATH

script:
    - |
      bats integration.bats


notifications:
  email: false
