language: rust
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/rust

rust:
  - stable

before_script:
  - |
      git clone https://github.com/sstephenson/bats/ &&
      cargo install --git https://github.com/semantic-rs/semantic-rs &&
      mkdir $HOME/workspace &&
      cp -r fixture/* $HOME/workspace/ &&
      export PATH=$(pwd)/bats/bin:$HOME/.cargo/bin:$PATH

script:
    - |
      bats integration.bats


notifications:
  email:
    on_success: never
