language: rust
sudo: required
dist: trusty

rust:
  - stable

before_script:
  - |
      git clone https://github.com/sstephenson/bats/ &&
      cargo install --git https://github.com/semantic-rs/semantic-rs &&
      export PATH=$(pwd)/bats/bin:$HOME/.cargo/bin:$PATH

script:
    - |
      pushd semantic-rs; cargo build --release; popd
      bats integration.bats


notifications:
  email:
    on_success: never
